name: openmfp-webcomponents
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}-wc
      cancel-in-progress: false
    uses: openmfp/gha/.github/workflows/pipeline-node-module.yml@main
    secrets: inherit
    with:
      publishFromDist: true
      workingDirectoryDist: ./dist/webcomponents
      artifactPath: dist/webcomponents
      environment: npmjs:@openmfp/webcomponents
